### ISSUE TITLE
symengine does not return unique objects for symbols with identical names

### ISSUE THREAD

**Issue by phantomas1234** [symengine/symengine.py#122]
In [1]: import sympy

	In [2]: id(sympy.Symbol('a'))
	Out[2]: 4615360016

	In [3]: id(sympy.Symbol('a'))
	Out[3]: 4615360016

	In [4]: import symengine

	In [5]: id(symengine.Symbol('a'))
	Out[5]: 4615766328

	In [6]: id(symengine.Symbol('a'))
	Out[6]: 4615766352

Is this intended? Unfortunately this breaks my attempts to swap sympy with symengine in a package I am working on as I am relying on sympy's behavior. On symengine.py=='0.1.0.dev' and symengine==0.2.0 (both installed using conda).

**Comment by isuruf** [comment]
This is known. SymPy has a cache and it will return the same object, but in SymPy also if the cache grows between the two calls and the first object is thrown away due to the cache being full, the same object might not be returned.

If it helps, can you describe the use of having the same id? Maybe there'll be a workaround.

**Comment by isuruf** [comment]
Here's a sympy example,
```python
In [20]: id(sympy.Symbol('a'))
Out[20]: 140585464811096

In [21]: id(sympy.Symbol('a'))
Out[21]: 140585464811096

In [22]: for i in range(1000000):
    ...:     t = sympy.Symbol('x%s'%i)
    ...:     

In [23]: id(sympy.Symbol('a'))
Out[23]: 140585467298728
```

**Comment by phantomas1234** [comment]
Ok, I didn't realize it is the cache that is causing this behavior, thanks.
