### ISSUE TITLE
Problem with subclassing symengine.Symbol

### ISSUE THREAD

**Issue by KristianJensen** [symengine/symengine.py#123]
Hi

I'm trying to define a subclass of Symbol to add extra functionalities to the class, but keeping the arithmetic properties the same.
However when one or more of these objects are combined in an expression, e.g. added together, the resulting Add object contains instances of symengine.Symbol instead of my subclass.

```python
import symengine

# Subclass of Symbol with an extra attribute
class Wrapper(symengine.Symbol):
    def __new__(cls, name, extra_attribute):
        return symengine.Symbol.__new__(cls, name)

    def __init__(self, name, extra_attribute):
        self.extra_attribute = extra_attribute
        super(Wrapper, self).__init__()

# I can instantiate the subclass
x = Wrapper("x", extra_attribute=3)

x.extra_attribute
>>> 3

# I then try to multiply the object by 2
two_x = 2 * x

two_x.args[1] is x
>>> False

# The argument of the expression is now a normal symengine Symbol object
type(two_x.args[1])
>>> symengine.lib.symengine_wrapper.Symbol
```

Is this a bug or is it intended behaviour?

**Comment by isuruf** [comment]
It's not intended, but it happens because of the design.
When a Symbol is created, a Symbol in the C++ is also created and this C++ object is referenced in the Python Symbol.
Arithmetic operations happen on the C++ side and therefore it knows only about the C++ object, not the Python object and when args is called it gives back a new Python object wrapping the C++ object.

One possible solution for this would be to subclass the C++ object and keep a pointer to the python object and return the python object instead of creating a new Python object wrapping the C++ object.
One disadvantage over this is that this creates a cyclic reference and the symbols are never freed.
