### ISSUE TITLE
don't delegate to SymPy on flint series exception

### ISSUE THREAD

**Issue by rwst** [symengine/symengine.py#47]
(I have to stack things up here to not forget them...)
Somewhere in symgenine.py this exception is not caught:
```
In [2]: from symengine import *

In [3]: x=Symbol('x')                      

In [4]: series(1/cos(x/log(x)), x, 0)
Out[4]: 
         2            4   
        x          5⋅x         ⎛ 6⎞
1 + ───────── + ────────── + O⎝x ⎠
         2            4       
    2⋅log (x)   24⋅log (x)  

In [5]: series(1/cos(x/log(x)), x, 0, method='symengine')
Exception (fmpq_poly_log_series). Constant term != 1.

Abort caught. Printing stacktrace:

Traceback (most recent call last):

Done.
Aborted
```
This SymPy test case is also interesting because, although univariate and having `log(x)`, SymPy solves it by leaving the log as were it another symbol. This shows the cases nomally throwing exceptions with `URatP...` can be treated by other means.

**Comment by certik** [comment]
Yes, this is common practice, see e.g.:

http://www.wolframalpha.com/input/?i=Series[1%2FCos[x%2FLog[x]],+{x,+0,+10}]

It would be nice to formalize that, but essentially log(x) grows slower than x, so this series makes sense. E.g. `x/log(x)` for small positive `x` is a beautiful function, going to zero (of course, for x=1 it's singular, but that's another issue).

Again, it would be nice to formalize this, but my intuition is telling me that this series is the best that you can do, since you can't expand `log(x)` around zero.

It is also used in the SymPy's limit algorithm.

**Comment by rwst** [comment]
We should just catch exceptions from our series and call SymPy instead (and I thought I had implemented it but...)

**Comment by certik** [comment]
Actually, I was going to ask about it --- I would let the exception propagate. If the user is calling `symengine`, then it should fail if symengine can't do it.

**Comment by rwst** [comment]
Ah ok, that was before you introduced `method=`.

**Comment by rwst** [comment]
So, this issue should fix this too.

**Comment by rwst** [comment]
Synopsis: Flint's C layer does not have exceptions. It simply prints a message and calls `abort()`. The only layer aware of this is Teuchos which has installed a signal handler that tries to print a stacktrace. I don't think we can throw a `RuntimeError` at that point in time.

So this must be handled by catching all conditions in SymEngine that can lead to a Flint abort before Flint is called. So we opened a SymEngine issue instead: https://github.com/symengine/symengine/issues/793

**Comment by rwst** [comment]
Reopened because the issue of not delegating needs resolve.
