### ISSUE TITLE
ImportError: symengine/lib/symengine_wrapper.so: undefined symbol: 

### ISSUE THREAD

**Issue by jasonrong001** [symengine/symengine.py#51]
I installed the python wrapper, and when I tried the examples 

`>>> from symengine import var`

the following error appeared:

```
File "symengine/__init__.py", line 1, in <module>
    from .lib.symengine_wrapper import (Symbol, Integer, sympify, SympifyError,
ImportError: symengine/lib/symengine_wrapper.so: undefined symbol: _ZNK9SymEngine14FunctionSymbol4subsERKSt3mapIN7Teuchos3RCPIKNS_5BasicEEES6_NS_15RCPBasicKeyLessESaISt4pairIKS6_S6_EEE
```

I am no expert on either ubuntu system or python, so the issue might be naive, thank you

**Comment by rwst** [comment]
It appears your SymEngine version is so old that it does not have the `FunctionSymbol::subs` function implementation. Please specify which versions of symengine.py and SymEngine you used, so that we can have certainty with the diagnosis.

For the record, the demangled symbol is: `SymEngine::FunctionSymbol::subs(std::map<Teuchos::RCP<SymEngine::Basic const>, Teuchos::RCP<SymEngine::Basic const>, SymEngine::RCPBasicKeyLess, std::allocator<std::pair<Teuchos::RCP<SymEngine::Basic const> const, Teuchos::RCP<SymEngine::Basic const> > > > const&) const`

**Comment by jasonrong001** [comment]
Thank you so much for replying!
Initially I was using the latest version of both symengine and symengine.py
and it did not work, so I switched to
"symengine-ce51ca41a7d48468455a700a78daad9d7544ad0e" and reinstalled  and
symengine.py.
The same error appeared again.  I am using Python 2.7.6, by the way.

Jason

**Comment by jasonrong001** [comment]
I tried the combination
"symengine-ce51ca41a7d48468455a700a78daad9d7544ad0e" and
"symengine.py-ce9297fe9bd834b3c921ff8cb9d5d94e96d0b48c" and now it is
working!

Jason

**Comment by certik** [comment]
Yes, always use the `symengine` git commit listed in https://github.com/symengine/symengine.py/blob/master/symengine_version.txt. As to `symengine.py`, the I am glad that the version ce9297fe9bd834b3c921ff8cb9d5d94e96d0b48c works for you. The latest master doesn't work?

**Comment by jasonrong001** [comment]
I just tried the latest master of "symengine.py", and it is working. I must
have made some mistake earlier.
Thank you so much for your kind help!

Jason

**Comment by certik** [comment]
I am glad it's working. Thanks for the report and if you find further issues, please let us know.
